resources:
- name: fbeazt-src
  type: git
  source:
    uri: https://github.com/cackharot/fbeazt.git
    branch: master
    # paths: [Dockerfile]
# - name: base-img
#   type: docker-image
#   source:
#     repository: alpine
- name: fbeazt-image
  type: docker-image
  source:
    repository: 51.15.85.110:30400/fbeazt/fbeazt-api:latest
    insecure_registries:
    - "51.15.85.110:30400"

jobs:
- name: fetch
  serial: true
  plan:
  # - aggregate:
  - get: fbeazt-src
    trigger: true
  # - get: base-img
- name: tests
  plan:
  - get: fbeazt-src
    trigger: true
    passed: [fetch]
  - task: src-package
    file: fbeazt-src/ci/tasks/tests.yml
- name: package
  plan:
  - get: fbeazt-src
    trigger: true
    passed: [tests]
  - put: fbeazt-image
    params:
      load_base: base-img
      dockerfile: fbeazt-src/ci/docker/api/Dockerfile
      # build: fbeazt-src
