version: '2'
services:
  namak-api:
    build: ./api
    ports:
      - "5000:4000"
    volumes:
      - ../:/opt/fbeazt
      - ./api/config/dev:/opt/fbeazt/src/foodbeazt/config
      - ./api/config/uwsgi:/etc/uwsgi/sites-enabled
    environment:
      FOODBEAZT_CONFIG: /opt/fbeazt/src/foodbeazt/config/foodbeazt.cfg
      MONGO_HOST: triton-mongodb
    extra_hosts:
      - "logstash-server:$DOCKERHOST"
    depends_on:
      - triton-mongodb
      - norma-lb

  triton-mongodb:
    build: ./database
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db

  #yuki-web:
    #build: ./web
    #ports:
      #- "9900:8080"
    #environment:
      ## NODE_ENV: production
      #NODE_ENV: development
    ## volumes:
      # - ../:/opt/fbeazt

  norma-lb:
    build: ./loadbalancer
    ports:
      - "8000:80"
      - "8800:8080"
      - "4333:433"
    volumes:
      - ./loadbalancer/conf.d:/etc/nginx/conf.d
